.TH CURSEOFWAR "1" "July 2013" "curseofwar " "User Commands"
.SH NAME
curseofwar \- Real Time Strategy Game for Linux
.SH DESCRIPTION
This is a fast-paced action strategy game for Linux implemented using ncurses user interface.
.PP
Unlike most RTS, you are not controlling units, but focus on high-level strategic planning: Building infrastructure, securing resources, and moving your armies.
.PP
The core game mechanics turns out to be quite close to WWI-WWII type of warfare, however, there is no explicit reference to any historical period.
.SH EXAMPLES
A good and easy mode to start playing:
.IP
.B curseofwar 
-i4 -q1 -dee
.PP
Or, on a smaller map:
.IP
.B curseofwar 
-i4 -q1 -dee -W16 -H16
.SH OPTIONS
.TP
\fB\-W\fR width
Map width (default is 21)
.TP
\fB\-H\fR height
Map height (default is 21)
.TP
\fB\-S\fR [rhombus|rect|hex]
Map shape (rectangle is default). Max number of countries N=4 for rhombus and rectangle, and N=6 for the hexagon.
.TP
\fB\-l\fR [2|3| ... N]
Sets L, the number of countries (default is N).
.TP
\fB\-i\fR [0|1|2|3|4]
Inequality between the countries (0 is the lowest, 4 in the highest).
.TP
\fB\-q\fR [1|2| ... L]
Choose player's location by its quality (1 = the best available on the map, L = the worst). Only in the singleplayer mode.
.TP
\fB\-r\fR
Absolutely random initial conditions, overrides options \fB\-l\fR, \fB\-i\fR, and \fB\-q\fR.
.TP
\fB\-d\fR [ee|e|n|h|hh]
Difficulty level (AI) from the easiest to the hardest (default is normal).
.TP
\fB\-s\fR [p|sss|ss|s|n|f|ff|fff]
Game speed from the slowest to the fastest (default is normal).
.TP
\fB\-R\fR seed
Specify a random seed (unsigned integer) for map generation.
.TP
\fB\-E\fR [1|2| ... L]
Start a server for not more than L clients.
.TP
\fB\-e\fR port
Server's port (19140 is default).
.TP
\fB\-C\fR IP
Start a client and connect to the provided server's IP\-address.
.TP
\fB\-c\fR port
Clients's port (19150 is default).
.TP
\fB\-h\fR
Display this help
.SH "SEE ALSO"
Curse of War wiki and homepage: https://github.com/a-nikolaev/curseofwar/wiki
.PP
More info in README file
.SH AUTORS
.B
Curseofwar author: 
Alexey Nikolaev\n
.br
.B
Manpage author: 
Anton Balashov <sicness@darklogic.ru>

